### ISSUE TITLE
Recovery issue

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#300]
```
I/flutter (12692): [Matrix] TomBootstrapDialogState::build(): BootstrapState = BootstrapState.openExistingSsss
I/flutter (12692): [Matrix] SSSS unlocked
I/flutter (12692): [Matrix] Unable to unlock SSSS - Exception: Master pubkey key doesn't match
I/flutter (12692): #0      CrossSigning.selfSign (package:matrix/encryption/cross_signing.dart:108:7)
I/flutter (12692): <asynchronous suspension>
I/flutter (12692): #1      TomBootstrapDialogState._unlockBackUp (package:fluffychat/pages/bootstrap/tom_bootstrap_dialog.dart:201:7)
I/flutter (12692): <asynchronous suspension>
I/flutter (12692): 
```

**Comment by hoangdat** [comment]
Testing with Element also:
- Create a backup (recovery)
- Chat on Monday
- Verify in next days
